import Config
secret_key_base = "6ppAsPtLGKFTuwVQ++fDT3Y/e9scyttz7hQCNt5k5HNdnzp8aOr6YoT+Fh6lINQy"

config :matt_van_horn,
       MattVanHornWeb.PersonalEndpoint,
       http: [ip: {127, 0, 0, 1}, port: 4791],
       check_origin: false,
       code_reloader: true,
       debug_errors: true,
       secret_key_base: secret_key_base

config :matt_van_horn,
       MattVanHornWeb.ProxyEndpoint,
       http: [ip: {127, 0, 0, 1}, port: 4000],
       check_origin: false,
       debug_errors: true,
       secret_key_base: secret_key_base

# Configure your database
config :matt_van_horn, MattVanHorn.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "matt_van_horn_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to loopback ipv4 address prevents access from other machines.
config :matt_van_horn, MattVanHornWeb.Endpoint,
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4100],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: secret_key_base,
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:matt_van_horn, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:matt_van_horn, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :matt_van_horn, MattVanHornWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/matt_van_horn_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :matt_van_horn, dev_routes: true, token_signing_secret: "guyPKEsQZfPACpNcoZV20aXwsPXKQ/dC"

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
